version: '3.8'

services:
  fastapi:
    build: ./fastapi_app
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - fastapi
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    image: redis:7
    ports:
      - "6379:6379"
